#!/usr/bin/env python3
"""Generate the handbook command-line reference (Appendix E) from each
example's ns-3 --PrintHelp output. Standard library only."""
import argparse
import difflib
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

_OPTION_RE = re.compile(
    r"^\s+--(?P<name>[A-Za-z0-9_]+):\s+"
    r"(?P<desc>.*?)(?:\s+\[(?P<default>[^\]]*)\]\s*)?$"
)


@dataclass(frozen=True)
class Option:
    name: str
    default: str
    description: str


def parse_print_help(text):
    """Parse the 'Program Options:' block of ns-3 --PrintHelp output.
    Returns a list[Option]; the 'General Arguments:' block is excluded."""
    options = []
    in_section = False
    for line in text.splitlines():
        if line.strip() == "Program Options:":
            in_section = True
            continue
        if line.strip() == "General Arguments:":
            break
        if in_section:
            m = _OPTION_RE.match(line)
            if m:
                options.append(
                    Option(
                        name=m.group("name"),
                        default=m.group("default") or "",
                        description=m.group("desc").strip(),
                    )
                )
    return options


_BANNER = (
    "# Appendix E — Command-line reference\n\n"
    "> Generated by `scripts/gen-cli-reference.py` from each example's ns-3\n"
    "> `--PrintHelp` output. Do not hand-edit — run the generator to refresh.\n\n"
    "Every example self-documents its options at the terminal:\n\n"
    "```bash\n"
    "./ns3 run \"<example> --PrintHelp\"\n"
    "```\n\n"
    "This appendix is a snapshot of that output for the runnable examples. For "
    "what each example *does*, see the [examples catalogue](I-08-examples-catalog.md); "
    "for options whose values are themselves a catalogue, pass `--<flag>=list` "
    "(for example `--aqm=list`, `--scheduler=list`).\n"
)


def _cell(text):
    return text.replace("|", "\\|")


def render_appendix(sections):
    parts = [_BANNER]
    for name, options in sections:
        parts.append(f"\n## {name}\n")
        if not options:
            parts.append("\n_(no command-line options)_\n")
            continue
        parts.append("\n| Option | Default | Description |\n|---|---|---|\n")
        for o in options:
            default = f"`{_cell(o.default)}`" if o.default else ""
            parts.append(
                f"| `--{_cell(o.name)}` | {default} | {_cell(o.description)} |\n"
            )
    return "".join(parts)


# Internal-only tools excluded from the user-facing reference: live-netns
# bridge, calibration/replay diagnostics, smoke fixtures, and specialist
# cross-validation/advanced-topology programs. Denylist (not allowlist) so a
# new example appears in the reference automatically and the --check guard
# forces a refresh.
INTERNAL_ONLY = {
    "cake-stratum-bridge-router",
    "retx-calibration",
    "gold-policer-replay",
    "cake-flent-host-attribution-smoke",
    "cake-host-iso-jitter-floor",
    "diffserv-l4s-dualpi2-gprt-parity",
    "diffserv-hierarchical-l4s",
}


def user_facing_examples(examples_dir):
    names = sorted(p.stem for p in Path(examples_dir).glob("*.cc"))
    return [n for n in names if n not in INTERNAL_ONLY]


def harvest(examples, runner):
    return [(ex, parse_print_help(runner(ex))) for ex in examples]


def _ns3_runner(ns3_dir):
    def run(example):
        out = subprocess.run(
            ["./ns3", "run", "--no-build", f"{example} --PrintHelp"],
            cwd=ns3_dir, capture_output=True, text=True,
        )
        return out.stdout
    return run


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate handbook Appendix E (CLI reference).")
    ap.add_argument("--ns3-dir", required=True, help="ns-3 tree to run ./ns3 from")
    ap.add_argument("--examples-dir", default="src/ns-3/examples",
                    help="directory of example .cc files")
    ap.add_argument("--out", default="handbook/appendix-E-cli-reference.md",
                    help="output markdown path")
    ap.add_argument("--check", action="store_true",
                    help="regenerate and diff against --out; nonzero on drift")
    args = ap.parse_args(argv)

    examples = user_facing_examples(args.examples_dir)
    content = render_appendix(harvest(examples, _ns3_runner(args.ns3_dir)))

    if args.check:
        current = Path(args.out).read_text() if Path(args.out).exists() else ""
        if current != content:
            sys.stdout.writelines(difflib.unified_diff(
                current.splitlines(keepends=True), content.splitlines(keepends=True),
                fromfile=args.out, tofile="(regenerated)"))
            print(f"\ncli-reference: {args.out} is STALE — run gen-cli-reference.py to refresh.")
            return 1
        print(f"cli-reference: {args.out} matches the binaries.")
        return 0

    Path(args.out).write_text(content)
    print(f"cli-reference: wrote {args.out} ({len(examples)} examples).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
